# Generated by Django 2.0.1 on 2018-01-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cruiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruiser_class', models.CharField(max_length=200)),
                ('build_date', models.DateTimeField(verbose_name='date building')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_parametrs', models.CharField(max_length=200)),
                ('shot', models.IntegerField(default=0)),
                ('cruiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duku.Cruiser')),
            ],
        ),
    ]
